### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by ui4j** [tdebatty/java-string-similarity#5]
Hi,

Could you please document the if NormalizedLevenshtein or other implementation class is thread safe or not.

Thanks

**Comment by tdebatty** [comment]
Hi,

Currently, none of them can be considered thread safe. I might add some thread safe wrapper classes (as soon as I get some time). In the meantime I will leave this issue open...

Best regards,

Thibault

**Comment by DwayneSmurdon** [comment]
I might also add that at the same time we update these to use Java 8, so that we can safely use parallelStream().  

I can potentially see two options here:  The methods themselves can use parallelStream() or we can just make it safe for the caller to use parallelStream() on a list of words they are processing.  There are probably other considerations and thoughts, but this is just off the top of my head right now.

**Comment by mpkorstanje** [comment]
If you need thread-safety you may want to look at [Simmetrics](https://github.com/Simmetrics/simmetrics). If you are going to compare N x N strings based on their tokens, do consider tokenizing them first and comparing the N x N token sets instead.

**Comment by tdebatty** [comment]
Hi,
I finished checking the different classes and they are all thread safe now. I also marked them with Immutable annotation.
Best regards,
