### ISSUE TITLE
using this code in netbeans 12.5

### ISSUE THREAD

**Issue by coreyjacob486** [tdebatty/java-string-similarity#62]
Hi here, 
I want to use this algorithm for a problem i'm trying to solve between and inventory excel and images related to the products inside the excel spreedsheet so i'm working into my own code in Netbeans 12.5 with Java but i'm not able to use them i tried to clone the code and the librarie into the project creat and object 
        Cosine cosine = new Cosine(2);
for example but there is no reference for importing the class. i tried also to make an import of the package
import src.test.java.info.debatty.java.*;
but still not working. I am not a full Java developer , i just trying to solve a problem but with Software, if you can give a better guide of how to implement it, much appreciate it.

**Comment by tdebatty** [comment]
Dear,

I think the problem is you should first:

1. download the jar from the releases page: https://github.com/tdebatty/java-string-similarity/releases
2. import the jar in your netbeans project

You can find some on explanation on stackoverflow: https://stackoverflow.com/questions/4879903/how-to-add-a-jar-in-netbeans

Regards!
